Fix fatal error due to missing Carbon classes
This fixes the following error which may occur with the `rocketeer.phar`:

> Fatal error: Class 'Carbon\Carbon' not found in .../LocalCloneStrategy.php on line 85